// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1caef347-cc1e-471e-9700-0197868b28e3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZdUZIaMwH",
    "aws_user_pools_web_client_id": "590pf42836effoaki8q24461i",
    "oauth": {}
};


export default awsmobile;
